# Generated by Django 3.1.5 on 2021-06-29 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('My_tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tasks',
            new_name='Task',
        ),
    ]
